---
- name: Setup symlinks for scripts
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: ~/.config/.scripts
    mode: u=rwx,go=r
    state: link

- name: Setup home ".bin" folder for globally accessible scripts for current user
  ansible.builtin.file:
    path: ~/.bin
    state: directory
    mode: u=rwx,go=r

- name: Setup global symlinks for scripts
  loop:
    - { name: git-delete-branches, as: gdb }
  ansible.builtin.file:
    src: "{{ role_path }}/files/{{ item.name }}"
    dest: "~/.bin/{{ item.as }}"
    mode: u=rwx,go=r
    state: link
