---
- name: Setup symlinks for scripts
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: ~/.config/.scripts
    mode: u=rwx,go=r
    state: link

- name: Setup user scripts folder
  ansible.builtin.file:
    path: ~/.bin
    state: directory
    mode: u=rwx,go=r

- name: Setup global symlinks for scripts
  ansible.builtin.file:
    src: "{{ role_path }}/files/git-delete-branches"
    dest: ~/.bin/gdb
    mode: u=rwx,go=r
    state: link
