---
package_management_brew_taps:
  - sst/tap
  - withgraphite/tap

package_management_brew_formula_packages:
  # Formulae
  - age
  - antidote
  - btop
  - direnv
  - fd
  - fzf
  - git-delta
  - jj
  - jq
  - lame
  - lazygit
  - mise
  - nasm
  - neovim
  - nushell
  - openssh
  - pi-coding-agent
  - pkgconf
  - ripgrep
  - sops
  - sshpass
  - sst/tap/opencode
  - starship
  - tealdeer
  - tree-sitter-cli
  - try-rs
  - viu
  - wget
  - withgraphite/tap/graphite
  - yazi
  - zsh
  # Casks
  - homebrew/cask/amethyst
  - homebrew/cask/anytype
  - homebrew/cask/claude-code@latest
  - homebrew/cask/codex
  - homebrew/cask/discord
  - homebrew/cask/ente
  - homebrew/cask/ente-auth
  - homebrew/cask/filen
  - homebrew/cask/font-hack-nerd-font
  - homebrew/cask/font-jetbrains-mono
  - homebrew/cask/font-jetbrains-mono-nerd-font
  - homebrew/cask/freetube
  - homebrew/cask/ghostty
  - homebrew/cask/gifox
  - homebrew/cask/google-drive
  - homebrew/cask/helium-browser
  - homebrew/cask/iina
  - homebrew/cask/mailspring
  - homebrew/cask/microsoft-teams
  - homebrew/cask/onlyoffice
  - homebrew/cask/orbstack
  - homebrew/cask/proton-drive
  - homebrew/cask/proton-pass
  - homebrew/cask/raycast
  - homebrew/cask/rustdesk
  - homebrew/cask/shottr
  - homebrew/cask/signal
  - homebrew/cask/slack
  - homebrew/cask/standard-notes
  - homebrew/cask/superwhisper
  - homebrew/cask/t3-code@nightly
  - homebrew/cask/tailscale-app
  - homebrew/cask/telegram
  - homebrew/cask/thaw
  - homebrew/cask/ungoogled-chromium
  - homebrew/cask/viber
  - homebrew/cask/whatsapp
  - homebrew/cask/yaak
  - homebrew/cask/zen
  - homebrew/cask/zentty
