---
brew_formula_packages:
  # Formulae
  - age
  - antidote
  - btop
  - cirruslabs/cli/tart
  - direnv
  - fd
  - fzf
  - jj
  - jq
  - lame
  - lazygit
  - mise
  - nasm
  - neovim
  - nushell
  - openssh
  - pi-coding-agent
  - pkgconf
  - ripgrep
  - sops
  - sshpass
  - sst/tap/opencode
  - starship
  - tealdeer
  - tmux
  - tree-sitter-cli
  - try-rs
  - viu
  - wget
  - withgraphite/tap/graphite
  - yazi
  - zsh
  # Casks
  - homebrew/cask/amethyst
  - homebrew/cask/anytype
  - homebrew/cask/claude-code
  - homebrew/cask/codex
  - homebrew/cask/discord
  - homebrew/cask/ente
  - homebrew/cask/ente-auth
  - homebrew/cask/filen
  - homebrew/cask/font-hack-nerd-font
  - homebrew/cask/font-jetbrains-mono
  - homebrew/cask/font-jetbrains-mono-nerd-font
  - homebrew/cask/freetube
  - homebrew/cask/ghostty
  - homebrew/cask/gifox
  - homebrew/cask/google-drive
  - homebrew/cask/helium-browser
  - homebrew/cask/iina
  - homebrew/cask/mailspring
  - homebrew/cask/microsoft-teams
  - homebrew/cask/onlyoffice
  - homebrew/cask/orbstack
  - homebrew/cask/proton-drive
  - homebrew/cask/raycast
  - homebrew/cask/shottr
  - homebrew/cask/signal
  - homebrew/cask/slack
  - homebrew/cask/standard-notes
  - homebrew/cask/superwhisper
  - homebrew/cask/t3-code
  - homebrew/cask/tailscale-app
  - homebrew/cask/telegram
  - homebrew/cask/thaw
  - homebrew/cask/ungoogled-chromium
  - homebrew/cask/viber
  - homebrew/cask/whatsapp
  - homebrew/cask/yaak
  - homebrew/cask/zen

arch_packages:
  - aur/anytype-bin
  - aur/ente-auth-bin
  - aur/ente-desktop-bin
  - aur/graphite-cli-git
  - aur/helium-browser-bin
  - aur/mailspring-bin
  - aur/onlyoffice-bin
  - aur/opencode-bin
  - aur/pi-coding-agent
  - aur/standardnotes-bin
  - aur/try-rs-bin
  - aur/zen-browser-bin
  - aur/zsh-antidote
  - core/openssh
  - core/pkgconf
  - extra/age
  - extra/btop
  - extra/direnv
  - extra/discord
  - extra/fd
  - extra/fzf
  - extra/ghostty
  - extra/jq
  - extra/jujutsu
  - extra/lame
  - extra/lazygit
  - extra/mise
  - extra/nasm
  - extra/neovim
  - extra/nushell
  - extra/ripgrep
  - extra/sops
  - extra/starship
  - extra/tailscale
  - extra/tealdeer
  - extra/tmux
  - extra/tree-sitter-cli
  - extra/ttf-hack-nerd
  - extra/ttf-jetbrains-mono
  - extra/ttf-jetbrains-mono-nerd
  - extra/viu
  - extra/wget
  - extra/yazi
  - extra/zsh
