---
- name: Check for "Homebrew"
  when: ansible_facts['os_family'] == 'Darwin'
  register: package_management_brew_check
  ansible.builtin.stat:
    path: /opt/homebrew/bin/brew

- name: Check for "Paru"
  when: ansible_facts['os_family'] == 'Archlinux'
  register: package_management_paru_check
  ansible.builtin.stat:
    path: /usr/bin/paru

- name: Install "Homebrew"
  when:
    - ansible_facts['os_family'] == 'Darwin'
    - not package_management_brew_check.stat.exists
  changed_when: true
  ansible.builtin.shell: |
    /bin/bash -c "$(curl -fsSL \
      https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

- name: Install "Paru"
  when:
    - ansible_facts['os_family'] == 'Archlinux'
    - not package_management_paru_check.stat.exists
  kewlfft.aur.aur:
    use: makepkg
    state: present
    name: paru-bin

- name: Tap custom repositories
  when: ansible_facts['os_family'] == 'Darwin'
  community.general.homebrew_tap:
    url: https://git.rafr.dev/raf/codearts-tap.git
    name: raf/codearts-tap
    state: present

- name: Install Packages
  ansible.builtin.include_tasks: packages.yml
