---
- name: Check for "Homebrew"
  register: package_management_brew_check
  ansible.builtin.stat:
    path: /opt/homebrew/bin/brew

- name: Install "Homebrew"
  when: not package_management_brew_check.stat.exists
  changed_when: true
  ansible.builtin.shell: |
    /bin/bash -c "$(curl -fsSL \
      https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

- name: Install Packages
  ansible.builtin.include_tasks: packages.yml
