---
- name: Tap Homebrew Taps
  community.general.homebrew_tap:
    name: "{{ package_management_brew_taps }}"
    state: present

- name: Install Homebrew Formulae
  community.general.homebrew:
    update_homebrew: true
    state: present
    name: "{{ package_management_brew_formula_packages }}"
