---
- name: System Setup
  hosts: all
  roles:
    - git
    - ssh
    - zsh
    - nushell
    - tmux
    - nvim
    - scripts
    - ghostty
    - graphite
    - starship
    - package_management
    - agents
    - raycast-scripts
    - try-rs
    - tealdeer
    - web-apps
