#!/usr/bin/env bash

inside_git_repo="$(git rev-parse --is-inside-work-tree 2>/dev/null)"

if [ "$inside_git_repo" != "true" ]; then
	echo "Not in a git repo!"
	exit 0
fi

branches=$(git branch -l | awk '!/\*/ {print}')

if [ ${#branches} -eq 0 ]; then
	echo "No local branches to delete!"
	exit 0
fi

git branch -D $branches
