#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
	selected=$1
else
	selected=$(find -L ~ ~/code ~/code/.personal ~/code/.sources ~/.config -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
	exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

# TODO: Add default split pane for `Main` window
if [[ -z $TMUX ]] && [[ -z $tmux_running ]] || ! tmux has-session -t="$selected_name" 2>/dev/null; then
	tmux new-session -ds "$selected_name" -n "Main" -c "$selected"
	tmux new-window -dn "Tests" -t "$selected_name:" -c "$selected"
fi

if [[ -z $TMUX ]]; then
	# NOTE: When we're not running tmux, attach to the session
	tmux attach-session -t "$selected_name"
else
	# NOTE: When we're running tmux, switch to the session
	tmux switch-client -t "$selected_name"
fi
