---
- name: Find SSH files
  register: ssh_files
  ansible.builtin.find:
    paths: "{{ role_path }}/files"
    file_type: file
    recurse: false

- name: Create SSH directory
  become: true
  become_user: "{{ ansible_facts['user_id'] }}"
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/.ssh"
    state: directory
    mode: "0700"
    owner: "{{ ansible_facts['user_id'] }}"

- name: Copy SSH files
  when: (item.path | basename) != "config"
  become: true
  become_user: "{{ ansible_facts['user_id'] }}"
  ansible.builtin.copy:
    src: "{{ item.path }}"
    dest: "{{ ansible_facts['user_dir'] }}/.ssh/{{ item.path | basename }}"
    mode: "{{ '0644' if item.path.endswith('.pub') else '0600' }}"
    owner: "{{ ansible_facts['user_id'] }}"
  loop: "{{ ssh_files.files }}"
  loop_control:
    label: "{{ item.path | basename }}"

- name: Symlink SSH config
  become: true
  become_user: "{{ ansible_facts['user_id'] }}"
  ansible.builtin.file:
    src: "{{ role_path }}/files/config"
    dest: "{{ ansible_facts['user_dir'] }}/.ssh/config"
    state: link
    force: true
    owner: "{{ ansible_facts['user_id'] }}"
