---
- name: Find SSH files
  register: ssh_files
  ansible.builtin.find:
    paths: "{{ role_path }}/files"
    file_type: file
    recurse: false

- name: Check if SSH keys are setup
  register: ssh_keys_check
  ansible.builtin.stat:
    path: "~/.ssh/{{ item }}"
  loop: "{{ ssh_files.files | map(attribute='path') | map('regex_replace', '^.*/(.*)$', '\\1') | list }}"

- name: Copy SSH keys
  when: ssh_keys_check.results | selectattr('stat.exists', 'equalto', false) | list | length > 0
  become: true
  become_user: "{{ ansible_user_id }}"
  ansible.builtin.copy:
    src: "{{ role_path }}/files/"
    dest: ~/.ssh/
    mode: u+rw
    directory_mode: u+rwx
    owner: "{{ ansible_user_id }}"
