---
- name: Check if ZSH is already setup
  register: zsh_config_check
  ansible.builtin.stat:
    path: ~/.config/zsh

- name: Copy custom ".zshenv"
  when: not zsh_config_check.stat.exists
  ansible.builtin.file:
    src: "{{ role_path }}/files/.zshenv"
    dest: ~/.zshenv
    mode: u=rwx,go-w
    state: link

- name: Copy custom files
  when: not zsh_config_check.stat.exists
  ansible.builtin.file:
    src: "{{ role_path }}/files/zsh"
    dest: ~/.config/zsh
    mode: u=rwx,go-w
    state: link
