# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = '''
(\[$git_branch(\($git_commit\)):$git_status( | $git_state)\]): $directory
$hostname[$character](bold green)
'''

right_format = '(\($cmd_duration\))$all'

# Inserts a blank line between shell prompts# Use custom format
add_newline = true

# Sets user-defined palette
# Palettes must be defined _after_ this line
palette = "catppuccin_macchiato"

[bun]
format = '[$symbol($version)]($style)'

# Replace the '❯' symbol in the prompt with '➜'
[character]
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'

[cmd_duration]
format = '[$duration]($style)'
show_notifications = true
min_time_to_notify = 10_000
notification_timeout = 3_000

[conda]
format = '[$symbol$environment]($style)'
ignore_base = true

[deno]
format = '[🦕 $version](green bold)'

[directory]
fish_style_pwd_dir_length = 1

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style)'
truncation_length = 50
truncation_symbol = '../'

[git_commit]
format = '[\($hash$tag\)]($style)'

[git_state]
format = '\([$state( $progress_current / $progress_total)]($style)\)'

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'

[golang]
format = '[$symbol($version)]($style)'

[hostname]
format = '[$hostname@]($style)'
style = "bg:green fg:base"
ssh_only = true

[lua]
format = '[$symbol($version)]($style)'

[nodejs]
format = '[$symbol($version)]($style)'

[package]
disabled = true

[python]
format = '[${symbol}(${version})]($style)'

[status]
format = '[$symbol$status]($style)'

[sudo]
format = '[as $symbol]($style)'

[time]
disabled = false
time_format = '%T'
format = '[ at $time]($style)'

# Pallets must be defined *AFTER* `pallete`
[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"
