---
- name: Symlink AGENTS.md to OpenCode
  ansible.builtin.file:
    src: "{{ role_path }}/files/AGENTS.md"
    dest: ~/.config/opencode/AGENTS.md
    state: link
    force: true

- name: Symlink AGENTS.md to Codex
  ansible.builtin.file:
    src: "{{ role_path }}/files/AGENTS.md"
    dest: ~/.codex/AGENTS.md
    state: link
    force: true

- name: Symlink AGENTS.md to Claude
  ansible.builtin.file:
    src: "{{ role_path }}/files/AGENTS.md"
    dest: ~/.claude/AGENTS.md
    state: link
    force: true

- name: Symlink CLAUDE.md to Claude
  ansible.builtin.file:
    src: "{{ role_path }}/files/CLAUDE.md"
    dest: ~/.claude/CLAUDE.md
    state: link
    force: true

- name: Symlink AGENTS.md to Pi
  ansible.builtin.file:
    src: "{{ role_path }}/files/AGENTS.md"
    dest: ~/.config/pi/AGENTS.md
    state: link
    force: true
