set -g mouse on
set -g default-terminal "screen-256color"
set -g base-index 1
set -g focus-events on
set -g status-position top
set -s set-clipboard on
set -s escape-time 0
set -sa terminal-overrides ",xterm-256color:RGB"
setw -g window-status-separator ""
set-option -g renumber-windows on

unbind C-b
set -g prefix C-a
bind-key C-a send-prefix

bind r source-file ~/.config/tmux/tmux.conf

set-window-option -g mode-keys vi

if-shell -b 'test -n "$WSLENV"' 'bind-key -T copy-mode-vi v send-keys -X begin-selection'
if-shell -b 'test -n "$WSLENV"' 'bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel clip.exe'
# bind -T copy-mode-vi v send-keys -X begin-selection
# bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

bind -r ^ last-window

bind-key -r f run-shell "tmux neww ~/.config/.scripts/tmux-sessionizer"
bind-key -r '~' run-shell "tmux neww ~/.config/.scripts/tmux-sessionizer ~"
bind-key -r b run-shell "bash ~/.config/.scripts/git-branches"

is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\\S+/)?g?(view|l?n?vim?x?)(diff)?$'"
bind-key -n C-h if-shell "$is_vim" "send-keys C-h" "select-pane -L"
bind-key -n C-j if-shell "$is_vim" "send-keys C-j" "select-pane -D"
bind-key -n C-k if-shell "$is_vim" "send-keys C-k" "select-pane -U"
bind-key -n C-\\ if-shell "$is_vim" "send-keys C-\\" "select-pane -l"

bind -n § switch-client -T winjump
bind -T winjump 1 select-window -t 1
bind -T winjump 2 select-window -t 2
bind -T winjump 3 select-window -t 3
bind -T winjump 4 select-window -t 4
bind -T winjump 5 select-window -t 5
bind -T winjump 6 select-window -t 6
bind -T winjump 7 select-window -t 7
bind -T winjump 8 select-window -t 8
bind -T winjump 9 select-window -t 9
bind -T winjump 0 last-window

bind -n S-Left previous-window
bind -n S-Right next-window

set -g @catppuccin_flavor "macchiato"

set -g @catppuccin_window_status_style "basic"
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_default_fill "none"
set -g @catppuccin_window_current_fill "all"
set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_window_current_text "#W"

set -g @catppuccin_status_connect_separator "yes"
set -g @catppuccin_status_fill "icon"

set -g @catppuccin_application_color "#{@thm_yellow}"

set -g @catppuccin_directory_text "#{pane_current_path}"

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'catppuccin/tmux'

set -g status-right "#{E:@catppuccin_status_application}#{E:@catppuccin_status_directory}"
set -g status-left "#{E:@catppuccin_status_session}"

run '~/.config/tmux/tpm/tpm'
