---
- name: Setup neovim config
  ansible.builtin.file:
    src: "{{ role_path }}/files/nvim"
    dest: ~/.config/nvim
    mode: u=rwx,go=r
    state: link

- name: Setup custom config
  ansible.builtin.file:
    src: "{{ role_path }}/files/custom-nvim-config"
    dest: ~/.config/custom-nvim-config
    mode: u=rwx,go=r
    state: link
